SYSTEM_SUPER_ADMIN = "super_admin"

ORGANIZER_OWNER = "owner"
ORGANIZER_ADMIN = "admin"
ORGANIZER_MEMBER = "member"

ACTIVE_ORGANIZER_ROLES = (
    ORGANIZER_OWNER,
    ORGANIZER_ADMIN,
    ORGANIZER_MEMBER,
)

ORGANIZER_MANAGEMENT_ROLES = (
    ORGANIZER_OWNER,
    ORGANIZER_ADMIN,
)
